# Generated by Django 3.1.8 on 2022-06-05 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('client', models.CharField(default=None, max_length=100)),
                ('requested_by', models.CharField(default=None, max_length=100)),
                ('type', models.CharField(default=None, max_length=100)),
                ('description', models.CharField(default=None, max_length=200)),
                ('labels', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
