# Generated by Django 3.1.8 on 2022-06-03 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leadapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='currency',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='leads',
            name='symbol',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='leads',
            name='vat',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='leads',
            name='website',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='leads',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='leads',
            name='city',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='leads',
            name='company',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='leads',
            name='country',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='leads',
            name='owner',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='leads',
            name='phone',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='leads',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leads',
            name='state',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='leads',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Qualified', 'Qualified'), ('Discussion', 'Discussion'), ('Negotiation', 'Negotiation'), ('Won', 'Won'), ('Lost', 'Lost')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='leads',
            name='zip',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
