# Generated by Django 3.1.8 on 2022-06-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadapp', '0004_auto_20220603_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default=None, max_length=100)),
                ('l_name', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default=None, max_length=10)),
                ('skype', models.CharField(default=None, max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='None', max_length=20)),
            ],
        ),
    ]
